---
- name: Install package dependencies
  become: yes
  apt: pkg='{{ item }}'
  with_items: '{{ packages }}'
  tags:
    - setup

- name: Install python-pip
  become: yes
  command: easy_install pip
  when: ansible_distribution == 'Debian' and ansible_distribution_version <= '8'
  tags:
    - setup

- name: Install python-pip Debian >= 9
  become: yes
  command: apt install python-pip
  when: ansible_distribution == 'Debian' and ansible_distribution_version >= '9'
  tags:
    - setup

- name: Install docker-py
  become: yes
  command: pip install 'docker-py>=1.7.0'
  tags:
    - setup
