---
#- name: ensure apt cache is up to date
#  apt: update_cache=yes

- name: install packages (set in group_vars)
  apt: pkg={{ item }}
  with_items: packages

- name: copy psql-backup script
  template: src=psql-dump.sh dest=/usr/local/sbin/ mode=755

- name: copy cron for psql-backup script
  template: src=cron-pgdump dest=/etc/cron.d/pgdump mode=644

- name: copy pg_memory script
  copy: src=pg_memory.sh dest=/usr/local/bin owner=root group=root mode=0755

- name: copy sysctl config 
  copy: src=sysctl-db.conf dest=/etc/sysctl.d owner=root group=root mode=0644 force=no
